/** Client-safe Spanish place gazetteer for location autocomplete. */

export type SpanishPlaceSuggestion = {
  label: string;
  kind: "city";
  value: string;
  city: string;
};

type PlaceRow =
  | readonly [name: string, province: string, weight: number]
  | readonly [name: string, province: string, weight: number, aliases: readonly string[]];

function fold(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase();
}

function placeLabel(name: string, province: string) {
  return province && province !== name ? `${name}, ${province}` : name;
}

/**
 * Major municipalities and property-market towns.
 * Weight is relative prominence in suggestions (not exact population).
 */
const PLACES: readonly PlaceRow[] = [
  ["Madrid", "Madrid", 100],
  ["Barcelona", "Barcelona", 100],
  ["Valencia", "Valencia", 92, ["València"]],
  ["Sevilla", "Sevilla", 90, ["Seville"]],
  ["Zaragoza", "Zaragoza", 82],
  ["Málaga", "Málaga", 90, ["Malaga"]],
  ["Murcia", "Murcia", 80],
  ["Palma", "Islas Baleares", 82, ["Palma de Mallorca"]],
  ["Las Palmas de Gran Canaria", "Las Palmas", 76],
  ["Bilbao", "Bizkaia", 82],
  ["Alicante", "Alicante", 86, ["Alacant"]],
  ["Córdoba", "Córdoba", 72, ["Cordoba"]],
  ["Valladolid", "Valladolid", 70],
  ["Vigo", "Pontevedra", 70],
  ["Gijón", "Asturias", 66, ["Gijon"]],
  ["L'Hospitalet de Llobregat", "Barcelona", 68, ["Hospitalet"]],
  ["Vitoria-Gasteiz", "Álava", 66, ["Vitoria"]],
  ["A Coruña", "A Coruña", 70, ["La Coruña", "Coruna"]],
  ["Granada", "Granada", 80],
  ["Elche", "Alicante", 76, ["Elx"]],
  ["Oviedo", "Asturias", 65],
  ["Badalona", "Barcelona", 64],
  ["Terrassa", "Barcelona", 62],
  ["Sabadell", "Barcelona", 62],
  ["Cartagena", "Murcia", 72],
  ["Jerez de la Frontera", "Cádiz", 66, ["Jerez"]],
  ["Pamplona", "Navarra", 70, ["Iruña"]],
  ["Santa Cruz de Tenerife", "Santa Cruz de Tenerife", 70],
  ["Almería", "Almería", 70, ["Almeria"]],
  ["Fuenlabrada", "Madrid", 60],
  ["Leganés", "Madrid", 60],
  ["Donostia-San Sebastián", "Gipuzkoa", 76, ["San Sebastián", "San Sebastian", "Donostia"]],
  ["Burgos", "Burgos", 60],
  ["Albacete", "Albacete", 60],
  ["Castellón de la Plana", "Castellón", 65, ["Castellón", "Castelló", "Castellon"]],
  ["Santander", "Cantabria", 66],
  ["Alcorcón", "Madrid", 56],
  ["San Cristóbal de La Laguna", "Santa Cruz de Tenerife", 55, ["La Laguna"]],
  ["Logroño", "La Rioja", 60],
  ["Badajoz", "Badajoz", 60],
  ["Salamanca", "Salamanca", 66],
  ["Huelva", "Huelva", 60],
  ["Lleida", "Lleida", 60, ["Lerida"]],
  ["Tarragona", "Tarragona", 66],
  ["León", "León", 60, ["Leon"]],
  ["Cádiz", "Cádiz", 66, ["Cadiz"]],
  ["Jaén", "Jaén", 55, ["Jaen"]],
  ["Ourense", "Ourense", 50, ["Orense"]],
  ["Girona", "Girona", 66, ["Gerona"]],
  ["Lugo", "Lugo", 50],
  ["Cáceres", "Cáceres", 55, ["Caceres"]],
  ["Toledo", "Toledo", 62],
  ["Ciudad Real", "Ciudad Real", 50],
  ["Guadalajara", "Guadalajara", 55],
  ["Cuenca", "Cuenca", 46],
  ["Segovia", "Segovia", 52],
  ["Ávila", "Ávila", 46, ["Avila"]],
  ["Palencia", "Palencia", 45],
  ["Zamora", "Zamora", 45],
  ["Soria", "Soria", 40],
  ["Huesca", "Huesca", 46],
  ["Teruel", "Teruel", 42],
  ["Pontevedra", "Pontevedra", 52],
  ["Ceuta", "Ceuta", 40],
  ["Melilla", "Melilla", 40],
  ["Mérida", "Badajoz", 50, ["Merida"]],
  ["Santiago de Compostela", "A Coruña", 68],
  ["Getafe", "Madrid", 60],
  ["Móstoles", "Madrid", 60, ["Mostoles"]],
  ["Alcalá de Henares", "Madrid", 64, ["Alcala de Henares"]],
  ["Parla", "Madrid", 50],
  ["Alcobendas", "Madrid", 55],
  ["San Sebastián de los Reyes", "Madrid", 52],
  ["Pozuelo de Alarcón", "Madrid", 55],
  ["Las Rozas de Madrid", "Madrid", 54, ["Las Rozas"]],
  ["Majadahonda", "Madrid", 54],
  ["Boadilla del Monte", "Madrid", 50],
  ["Rivas-Vaciamadrid", "Madrid", 52, ["Rivas"]],
  ["Arganda del Rey", "Madrid", 48],
  ["Coslada", "Madrid", 50],
  ["Paterna", "Valencia", 55],
  ["Mislata", "Valencia", 48],
  ["Talavera de la Reina", "Toledo", 52],
  ["Reus", "Tarragona", 55],
  ["Mataró", "Barcelona", 58, ["Mataro"]],
  ["Cornellà de Llobregat", "Barcelona", 52],
  ["Sant Cugat del Vallès", "Barcelona", 55],
  ["Manresa", "Barcelona", 50],
  ["Barakaldo", "Bizkaia", 52],
  ["Getxo", "Bizkaia", 50],
  ["Irun", "Gipuzkoa", 48],

  // Costa Blanca / Alicante
  ["Torrevieja", "Alicante", 86],
  ["Benidorm", "Alicante", 82],
  ["Orihuela", "Alicante", 72],
  ["Dénia", "Alicante", 72, ["Denia"]],
  ["Calpe", "Alicante", 66, ["Calp"]],
  ["Altea", "Alicante", 60],
  ["Villajoyosa", "Alicante", 56, ["La Vila Joiosa"]],
  ["Guardamar del Segura", "Alicante", 62],
  ["Santa Pola", "Alicante", 62],
  ["Pilar de la Horadada", "Alicante", 62],
  ["Rojales", "Alicante", 56],
  ["Algorfa", "Alicante", 42],
  ["Ciudad Quesada", "Alicante", 50],
  ["San Fulgencio", "Alicante", 40],
  ["Daya Nueva", "Alicante", 35],
  ["Daya Vieja", "Alicante", 30],
  ["Formentera del Segura", "Alicante", 38],
  ["Benijófar", "Alicante", 40, ["Benijofar"]],
  ["Los Montesinos", "Alicante", 40],
  ["San Miguel de Salinas", "Alicante", 48],
  ["Almoradí", "Alicante", 46, ["Almoradi"]],
  ["Catral", "Alicante", 40],
  ["Callosa de Segura", "Alicante", 44],
  ["Cox", "Alicante", 35],
  ["Gran Alacant", "Alicante", 48],
  ["Jávea", "Alicante", 72, ["Xàbia", "Xabia", "Javea"]],
  ["Moraira", "Alicante", 58],
  ["Teulada", "Alicante", 52],
  ["Benissa", "Alicante", 50],
  ["El Campello", "Alicante", 55],
  ["Sant Joan d'Alacant", "Alicante", 48],
  ["Mutxamel", "Alicante", 46],
  ["San Vicente del Raspeig", "Alicante", 55, ["Sant Vicent del Raspeig"]],
  ["Novelda", "Alicante", 45],
  ["Elda", "Alicante", 50],
  ["Petrer", "Alicante", 46],
  ["Villena", "Alicante", 48],
  ["Alcoy", "Alicante", 52, ["Alcoi"]],
  ["Ibi", "Alicante", 42],
  ["La Nucía", "Alicante", 48, ["La Nucia"]],
  ["Finestrat", "Alicante", 48],
  ["Polop", "Alicante", 38],
  ["L'Alfàs del Pi", "Alicante", 55, ["Alfaz del Pi", "Alfàs del Pi"]],
  ["La Marina", "Alicante", 42],

  // Costa del Sol / Málaga
  ["Marbella", "Málaga", 88],
  ["Estepona", "Málaga", 80],
  ["Fuengirola", "Málaga", 80],
  ["Torremolinos", "Málaga", 82],
  ["Benalmádena", "Málaga", 76, ["Benalmadena"]],
  ["Mijas", "Málaga", 76],
  ["Nerja", "Málaga", 66],
  ["Torrox", "Málaga", 62],
  ["Manilva", "Málaga", 50],
  ["Casares", "Málaga", 46],
  ["San Roque", "Cádiz", 55],
  ["La Línea de la Concepción", "Cádiz", 55, ["La Linea"]],
  ["Sotogrande", "Cádiz", 58],
  ["Rincón de la Victoria", "Málaga", 56, ["Rincon de la Victoria"]],
  ["Vélez-Málaga", "Málaga", 56, ["Velez-Malaga"]],
  ["Alhaurín de la Torre", "Málaga", 54, ["Alhaurin de la Torre"]],
  ["Alhaurín el Grande", "Málaga", 48],
  ["Cártama", "Málaga", 46, ["Cartama"]],
  ["Coín", "Málaga", 46, ["Coin"]],
  ["Álora", "Málaga", 42, ["Alora"]],
  ["Antequera", "Málaga", 52],
  ["Ronda", "Málaga", 55],
  ["Estepona", "Málaga", 80],
  ["Mijas Costa", "Málaga", 70],
  ["Cancelada", "Málaga", 40],
  ["San Pedro Alcántara", "Málaga", 60, ["San Pedro de Alcántara"]],
  ["Puerto Banús", "Málaga", 58, ["Puerto Banus"]],
  ["Nueva Andalucía", "Málaga", 55, ["Nueva Andalucia"]],
  ["Elviria", "Málaga", 48],
  ["Cabopino", "Málaga", 42],
  ["La Cala de Mijas", "Málaga", 55],
  ["Benahavís", "Málaga", 52, ["Benahavis"]],
  ["Ojén", "Málaga", 40, ["Ojen"]],
  ["Istán", "Málaga", 36, ["Istan"]],
  ["Frigiliana", "Málaga", 42],
  ["Competa", "Málaga", 36],
  ["Sayalonga", "Málaga", 30],

  // Costa Cálida / Murcia
  ["Torre-Pacheco", "Murcia", 66, ["Torre Pacheco"]],
  ["Los Alcázares", "Murcia", 56, ["Los Alcazares"]],
  ["San Javier", "Murcia", 58],
  ["San Pedro del Pinatar", "Murcia", 56],
  ["Mazarrón", "Murcia", 55, ["Mazarron"]],
  ["Águilas", "Murcia", 55, ["Aguilas"]],
  ["La Manga del Mar Menor", "Murcia", 58, ["La Manga"]],
  ["Cartagena", "Murcia", 72],
  ["Lorca", "Murcia", 55],
  ["Molina de Segura", "Murcia", 52],
  ["Alcantarilla", "Murcia", 48],
  ["Yecla", "Murcia", 45],
  ["Jumilla", "Murcia", 42],
  ["Cieza", "Murcia", 42],
  ["Caravaca de la Cruz", "Murcia", 40],
  ["Puerto de Mazarrón", "Murcia", 50],
  ["Bolnuevo", "Murcia", 38],
  ["Condado de Alhama", "Murcia", 42],
  ["Hacienda del Álamo", "Murcia", 40],
  ["Roda Golf", "Murcia", 36],
  ["Mar Menor", "Murcia", 50],

  // Costa Brava / Catalonia coast
  ["Lloret de Mar", "Girona", 70],
  ["Blanes", "Girona", 60],
  ["Roses", "Girona", 60, ["Rosas"]],
  ["Empuriabrava", "Girona", 52],
  ["Castelló d'Empúries", "Girona", 48],
  ["Platja d'Aro", "Girona", 52, ["Playa de Aro"]],
  ["Sant Feliu de Guíxols", "Girona", 50],
  ["Tossa de Mar", "Girona", 52],
  ["Cadaqués", "Girona", 48, ["Cadaques"]],
  ["L'Escala", "Girona", 48],
  ["L'Estartit", "Girona", 46],
  ["Torroella de Montgrí", "Girona", 48],
  ["Palamós", "Girona", 50, ["Palamos"]],
  ["Calella", "Barcelona", 50],
  ["Pineda de Mar", "Barcelona", 48],
  ["Malgrat de Mar", "Barcelona", 46],
  ["Sitges", "Barcelona", 72],
  ["Vilanova i la Geltrú", "Barcelona", 55],
  ["Castelldefels", "Barcelona", 60],
  ["Gavà", "Barcelona", 50, ["Gava"]],
  ["Viladecans", "Barcelona", 50],
  ["El Prat de Llobregat", "Barcelona", 52],
  ["Salou", "Tarragona", 62],
  ["Cambrils", "Tarragona", 56],
  ["La Pineda", "Tarragona", 46],
  ["Calafell", "Tarragona", 50],
  ["El Vendrell", "Tarragona", 50],
  ["Coma-ruga", "Tarragona", 42],
  ["L'Ametlla de Mar", "Tarragona", 42],
  ["L'Ampolla", "Tarragona", 40],
  ["Sant Carles de la Ràpita", "Tarragona", 44],
  ["Deltebre", "Tarragona", 40],

  // Valencia coast
  ["Torrent", "Valencia", 76],
  ["Gandia", "Valencia", 72, ["Gandía"]],
  ["Cullera", "Valencia", 56],
  ["Oliva", "Valencia", 52],
  ["Daimús", "Valencia", 38],
  ["Bellreguard", "Valencia", 36],
  ["Xeraco", "Valencia", 38],
  ["Tavernes de la Valldigna", "Valencia", 42],
  ["Sueca", "Valencia", 46],
  ["Alzira", "Valencia", 52],
  ["Xàtiva", "Valencia", 50, ["Játiva", "Xativa"]],
  ["Ontinyent", "Valencia", 46],
  ["Algemesí", "Valencia", 42],
  ["Burjassot", "Valencia", 48],
  ["Mislata", "Valencia", 48],
  ["Manises", "Valencia", 48],
  ["Aldaia", "Valencia", 46],
  ["Quart de Poblet", "Valencia", 46],
  ["Sagunto", "Valencia", 55, ["Sagunt"]],
  ["Puçol", "Valencia", 44],
  ["El Puig", "Valencia", 42],
  ["Canet d'En Berenguer", "Valencia", 40],
  ["Peñíscola", "Castellón", 56, ["Peniscola", "Peníscola"]],
  ["Benicàssim", "Castellón", 52, ["Benicasim"]],
  ["Oropesa del Mar", "Castellón", 48, ["Orpesa"]],
  ["Vinaròs", "Castellón", 48, ["Vinaroz"]],
  ["Benicarló", "Castellón", 46],
  ["Alcossebre", "Castellón", 42],
  ["Alcalà de Xivert", "Castellón", 38],

  // Costa de la Luz / Cádiz / Huelva
  ["Chiclana de la Frontera", "Cádiz", 58],
  ["El Puerto de Santa María", "Cádiz", 60, ["Puerto de Santa Maria"]],
  ["Sanlúcar de Barrameda", "Cádiz", 52, ["Sanlucar de Barrameda"]],
  ["Rota", "Cádiz", 50],
  ["Chipiona", "Cádiz", 46],
  ["Conil de la Frontera", "Cádiz", 52],
  ["Vejer de la Frontera", "Cádiz", 44],
  ["Barbate", "Cádiz", 46],
  ["Zahara de los Atunes", "Cádiz", 42],
  ["Tarifa", "Cádiz", 56],
  ["Algeciras", "Cádiz", 58],
  ["Estepona", "Málaga", 80],
  ["Ayamonte", "Huelva", 46],
  ["Isla Canela", "Huelva", 44],
  ["Isla Cristina", "Huelva", 46],
  ["Punta Umbría", "Huelva", 48, ["Punta Umbria"]],
  ["El Rompido", "Huelva", 42],
  ["Cartaya", "Huelva", 44],
  ["Lepe", "Huelva", 46],
  ["Matalascañas", "Huelva", 44],
  ["Almonte", "Huelva", 44],

  // Granada / Almería coast
  ["Motril", "Granada", 52],
  ["Almuñécar", "Granada", 52, ["Almunecar"]],
  ["Salobreña", "Granada", 46, ["Salobrena"]],
  ["La Herradura", "Granada", 42],
  ["Roquetas de Mar", "Almería", 62],
  ["El Ejido", "Almería", 52],
  ["Adra", "Almería", 44],
  ["Carboneras", "Almería", 40],
  ["Mojácar", "Almería", 55, ["Mojacar"]],
  ["Vera", "Almería", 50],
  ["Garrucha", "Almería", 44],
  ["Cuevas del Almanzora", "Almería", 42],
  ["Pulpí", "Almería", 42, ["Pulpi"]],
  ["San Juan de los Terreros", "Almería", 44],
  ["Aguadulce", "Almería", 46],
  ["Almerimar", "Almería", 46],
  ["Retamar", "Almería", 40],
  ["Cabo de Gata", "Almería", 44],
  ["Níjar", "Almería", 42, ["Nijar"]],

  // Balearics
  ["Calvià", "Islas Baleares", 72, ["Calvia"]],
  ["Alcúdia", "Islas Baleares", 62, ["Alcudia"]],
  ["Manacor", "Islas Baleares", 55],
  ["Inca", "Islas Baleares", 48],
  ["Llucmajor", "Islas Baleares", 50],
  ["Marratxí", "Islas Baleares", 48],
  ["Sóller", "Islas Baleares", 50, ["Soller"]],
  ["Pollença", "Islas Baleares", 52, ["Pollensa", "Pollenca"]],
  ["Andratx", "Islas Baleares", 50],
  ["Santa Ponsa", "Islas Baleares", 52, ["Santa Ponça"]],
  ["Magaluf", "Islas Baleares", 50],
  ["Palma Nova", "Islas Baleares", 50],
  ["Portals Nous", "Islas Baleares", 48],
  ["Cala d'Or", "Islas Baleares", 50],
  ["Porto Cristo", "Islas Baleares", 46],
  ["Cala Millor", "Islas Baleares", 48],
  ["Cala Ratjada", "Islas Baleares", 48],
  ["Sa Coma", "Islas Baleares", 42],
  ["Colonia de Sant Jordi", "Islas Baleares", 42],
  ["Ibiza", "Islas Baleares", 82, ["Eivissa"]],
  ["Santa Eulària des Riu", "Islas Baleares", 62, ["Santa Eulalia"]],
  ["Sant Antoni de Portmany", "Islas Baleares", 60, ["San Antonio"]],
  ["Sant Josep de sa Talaia", "Islas Baleares", 52],
  ["Sant Joan de Labritja", "Islas Baleares", 42],
  ["Formentera", "Islas Baleares", 58],
  ["Maó", "Islas Baleares", 55, ["Mahón", "Mahon"]],
  ["Ciutadella de Menorca", "Islas Baleares", 56, ["Ciutadella"]],
  ["Es Mercadal", "Islas Baleares", 42],
  ["Fornells", "Islas Baleares", 42],

  // Canaries
  ["Adeje", "Santa Cruz de Tenerife", 72],
  ["Arona", "Santa Cruz de Tenerife", 70],
  ["Adeje Costa", "Santa Cruz de Tenerife", 60],
  ["Los Cristianos", "Santa Cruz de Tenerife", 62],
  ["Playa de las Américas", "Santa Cruz de Tenerife", 62, ["Las Americas"]],
  ["Costa Adeje", "Santa Cruz de Tenerife", 68],
  ["Puerto de la Cruz", "Santa Cruz de Tenerife", 62],
  ["Los Realejos", "Santa Cruz de Tenerife", 48],
  ["La Orotava", "Santa Cruz de Tenerife", 50],
  ["Candelaria", "Santa Cruz de Tenerife", 46],
  ["Guía de Isora", "Santa Cruz de Tenerife", 46],
  ["Santiago del Teide", "Santa Cruz de Tenerife", 44],
  ["Los Gigantes", "Santa Cruz de Tenerife", 50],
  ["Puerto de Santiago", "Santa Cruz de Tenerife", 48],
  ["San Bartolomé de Tirajana", "Las Palmas", 70],
  ["Maspalomas", "Las Palmas", 68],
  ["Playa del Inglés", "Las Palmas", 62, ["Playa del Ingles"]],
  ["Mogán", "Las Palmas", 60, ["Mogan"]],
  ["Puerto Rico", "Las Palmas", 55],
  ["Arguineguín", "Las Palmas", 48, ["Arguineguin"]],
  ["Meloneras", "Las Palmas", 50],
  ["Vecindario", "Las Palmas", 48],
  ["Telde", "Las Palmas", 55],
  ["Arrecife", "Las Palmas", 58],
  ["Teguise", "Las Palmas", 50],
  ["Tías", "Las Palmas", 55, ["Tias"]],
  ["Yaiza", "Las Palmas", 50],
  ["Puerto del Carmen", "Las Palmas", 62],
  ["Playa Blanca", "Las Palmas", 60],
  ["Costa Teguise", "Las Palmas", 58],
  ["Puerto Calero", "Las Palmas", 46],
  ["La Oliva", "Las Palmas", 52],
  ["Corralejo", "Las Palmas", 58],
  ["Morro Jable", "Las Palmas", 50],
  ["Pájara", "Las Palmas", 46, ["Pajara"]],
  ["Antigua", "Las Palmas", 42],
  ["Puerto del Rosario", "Las Palmas", 50],
  ["Valverde", "Santa Cruz de Tenerife", 36],

  // Other well-known Tor* municipalities
  ["Torrejón de Ardoz", "Madrid", 78, ["Torrejon de Ardoz"]],
  ["Torrelavega", "Cantabria", 60],
  ["Torredembarra", "Tarragona", 55],
  ["Torrelodones", "Madrid", 58],
  ["Tordesillas", "Valladolid", 46],
  ["Toro", "Zamora", 44],
  ["Tordera", "Barcelona", 48],
  ["Tortosa", "Tarragona", 58],
  ["Torelló", "Barcelona", 42, ["Torelló"]],
  ["Torà", "Lleida", 28, ["Tora"]],
  ["Toreno", "León", 28],
  ["Torrejón de la Calzada", "Madrid", 36],
  ["Torrejón de Velasco", "Madrid", 36],
  ["Torrejón del Rey", "Guadalajara", 32],
  ["Torrelaguna", "Madrid", 32],
  ["Torrelavit", "Barcelona", 30],
  ["Torreblanca", "Castellón", 42],
  ["Torredelcampo", "Jaén", 36],
  ["Torredonjimeno", "Jaén", 40],
  ["Torreperogil", "Jaén", 32],
  ["Torres", "Jaén", 28],
  ["Torrijos", "Toledo", 42],
  ["Torija", "Guadalajara", 26],
  ["Torroella de Fluvià", "Girona", 28],
  ["Torrefarrera", "Lleida", 28],
  ["Torregrossa", "Lleida", 26],
  ["Torrelles de Llobregat", "Barcelona", 32],
  ["Torrelles de Foix", "Barcelona", 24],
  ["Torreorgaz", "Cáceres", 22],
  ["Torrequemada", "Cáceres", 20],
  ["Torremocha de Jarama", "Madrid", 22],
  ["Torremocha del Campo", "Guadalajara", 20],
  ["Torremocha del Pinar", "Guadalajara", 18],
  ["Torrecilla de Alcañiz", "Teruel", 18],
  ["Torrecilla en Cameros", "La Rioja", 16],
  ["Torrecaballeros", "Segovia", 22],
  ["Torreiglesias", "Segovia", 16],
  ["Torres de la Alameda", "Madrid", 32],
  ["Torres de Segre", "Lleida", 24],
  ["Torresandino", "Burgos", 16],
  ["Torregalindo", "Burgos", 14],
  ["Torrecilla del Monte", "Burgos", 14],
  ["Tordómar", "Burgos", 14],
  ["Tordillos", "Salamanca", 14],
  ["Torresmenudas", "Salamanca", 14],
  ["Tormos", "Alicante", 22],
  ["Tornavacas", "Cáceres", 16],
  ["Torralba de Calatrava", "Ciudad Real", 24],
  ["Torralba de Oropesa", "Toledo", 16],
  ["Torralba del Pinar", "Castellón", 16],
  ["Tortuera", "Guadalajara", 14],
  ["Tortuero", "Guadalajara", 12],
  ["Tortellà", "Girona", 20],
  ["Torás", "Castellón", 14],
];

export function suggestSpanishPlaces(
  query: string,
  limit = 8,
): SpanishPlaceSuggestion[] {
  const q = fold(query.trim());
  if (q.length < 2) return [];

  const scored: {
    name: string;
    province: string;
    weight: number;
    score: number;
  }[] = [];

  for (const row of PLACES) {
    const name = row[0];
    const province = row[1];
    const weight = row[2];
    const aliases = row[3] ?? [];
    let score = 99;
    for (const candidate of [name, ...aliases]) {
      const f = fold(candidate);
      if (f === q) score = Math.min(score, 0);
      else if (f.startsWith(q)) score = Math.min(score, 1);
      else if (f.split(/[\s/-]+/).some((part) => part.startsWith(q))) {
        score = Math.min(score, 2);
      } else if (q.length >= 4 && f.includes(q)) {
        score = Math.min(score, 3);
      }
    }
    if (score === 99) continue;
    scored.push({ name, province, weight, score });
  }

  scored.sort(
    (a, b) =>
      a.score - b.score ||
      b.weight - a.weight ||
      a.name.localeCompare(b.name, "es"),
  );

  const seen = new Set<string>();
  const out: SpanishPlaceSuggestion[] = [];
  for (const place of scored) {
    const key = fold(place.name);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({
      kind: "city",
      value: place.name,
      city: place.name,
      label: placeLabel(place.name, place.province),
    });
    if (out.length >= limit) break;
  }
  return out;
}
